### ISSUE TITLE
Using nested `elastic-apm.yml` breaks application start

### ISSUE THREAD

**Issue by d3mash** [elastic/apm-agent-ruby#1020]
## Describe the bug

Using a nested YAML with aliases breaks application

```
rails s

Psych::BadAlias: Unknown alias: defaults
from /Users/demidkashirin/.rvm/gems/ruby-2.7.3/gems/psych-3.2.0/lib/psych/visitors/to_ruby.rb:428:in `visit_Psych_Nodes_Alias'
```

## Steps to reproduce

1. Install `elastic-apm` version 4.1.0 in a Rails environment
2. Create a config with the following:
```
defaults: &defaults
  server_url: localhost:8080
  transaction_sample_rate: 0.1

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
  server_url: host.host
production:
  <<: *defaults
  server_url: host.host

```
3. `bundle exec rails s`

## Expected behavior
Application starts correctly

## Environment

- **OS**: OS X
- **Ruby version**: 2.7.3
- **Framework and version**: Rails 6.0.1
- **APM Server version**: 7.13.1
- **Agent version**: 4.0.5

**Comment by mikker** [comment]
Hi @d3mash! Environment scoped config isn't supported. It's just a flat YAML file. You can use ERB, eg:

```yaml
server_url: <%= Rails.env.production? ? 'http://production' : 'http://development' %>
```

**Comment by d3mash** [comment]
Yeah, I see, but why is this so? I think that using `Rails.env` is a code smell 😞 

I think that we can use `alias: true` here

 https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/config.rb#L237

Not trying to be rude or anything, I just want to understand the reasoning behind no support for environment scoping

@mikker

**Comment by mikker** [comment]
Even though we added  `alias`, the config option would still be scoped under the environment key in the resulting hash. There's no promise that all config files are scoped by env just because `database.yml` is. In fact, Rails' own _credentials_ are also just a flat file, unknowing about the env. (https://edgeguides.rubyonrails.org/security.html#custom-credentials)

I have never heard about `Rails.env` being a code smell and I can't see why it would be so please elaborate why that is 😊
