### ISSUE TITLE
No traces generated for non-error, auto-instrumented spans

### ISSUE THREAD

**Issue by karn09** [elastic/apm-agent-ruby#386]
I'm currently trying to get span traces working on a Rails 5.0.7 project for auto-instrumented (via AS: Notifications) spans.

My expectation was that by setting `source_lines_span_app_frames` to a non-zero value, and `span_frames_min_duration` to -1, traces would be reported for all requests. Ideally, being able to later set `span_frames_min_duration` to a higher value so that code traces are reported alongside sql for slow spans. 

I started digging around a bit and found this PR https://github.com/elastic/apm-agent-ruby/pull/282, which addresses traces reported via `ElasticAPM.with_span`. With this though, it requires manually defining custom spans in the code.

It seems that the issue is that `caller` is not being used to set the `backtrace` within the subscriber agent [here](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/subscriber.rb#L43). 

I'd be happy to open a PR, which just changes the line to `@agent.start_span(name, type, backtrace: caller, context: context)`, but have several questions.

1. Is there a better place to use `caller`? For example, on [line #20](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/subscriber.rb#L20), as part of the subscription block. Not entirely sure how that would work though. 

2. Is there a reason to not do this? My thought is that since this will run every time a notification is sent (even if the eventual trace isn't always sent to the APM), some amount of overhead will be added. Perhaps the overhead is negligible? 

3. Or.. is this all unnecessary, and code traces can be turned on for spans via something I've not tried. 

Thanks!

**Comment by mikker** [comment]
Hi @karn09! Sorry for the slow response.

This would be very nice to have I simply haven't come around to it yet. You're of course very welcome to help out if you have the time.

To be honest I'm not quite sure where the best place to get the stacktrace would be. Probably like your first suggestion, perhaps popping a few lines off the top, so we don't start every trace with AS::Notification methods. Then again that would be _sort of_ lying. What do you think?

**Comment by estolfo** [comment]
We've found a way to get the stacktrace for Grape, but not Rails. Until Rails has an API for getting to the user's source code or info in the `payload` passed to the AS notifications subscriber hook, we can't do much. We'll close this issue as `resolved` for Grape, but `won't fix` for Rails.

**Comment by estolfo** [comment]
After much investigation and many trials, we've concluded that we can't get a stacktrace for Rails spans and can only get the source location of the user's code for Grape. In other words, the stacktrace for Grape spans will be one line long, consisting of the source location.

The reason we can't get stacktraces is because while many libraries (Grape and Rails included) provide a hook for instrumenters, they yield to a block when the user's code is called. We therefore have no way to get a stacktrace from within the block code.

As an alternative, we recommend looking at how you can create a custom span or span entire methods. This would allow a stacktrace to be collected. Please see [here](https://www.elastic.co/guide/en/apm/agent/ruby/2.x/custom-instrumentation.html) for the documentation.
