### ISSUE TITLE
Don't nag users when opening console

### ISSUE THREAD

**Issue by liamwhite** [elastic/apm-agent-ruby#445]
IOW, don't do this:
```
vagrant@test:~/test$ rails c
I, [2019-06-15T23:27:12.014406 #3550]  INFO -- : [ElasticAPM] Skipping because: Rails console. Start manually with `ElasticAPM.start'
Loading development environment (Rails 5.2.3)
irb(main):001:0>
```
Do this:
```
vagrant@test:~/test$ rails c
Loading development environment (Rails 5.2.3)
irb(main):001:0>
```

---

I would also strongly recommend against this project having an "alert logger" with a separate log level from the one specified in the configuration. I ended up doing this in my application because I was quite tired of the verbosity of the logger:
```rb
    # ElasticAPM has a lot of useless debug logging
    Rails.application.config.elastic_apm.alert_logger = Logger.new(nil)
```

**Comment by liamwhite** [comment]
Because someone is probably going to ask: i am aware of the option named `disable_start_message`. I don't think that this should even have to exist; it's a terrible default to nag users for doing expected behavior. I also get unrelated logger warnings that are entirely superfluous during development, and `disable_start_message` does not take care of those, which is why I am not using that here.

**Comment by mikker** [comment]
Hi @liamwhite. I get your message – I like my logs quiet too. The messages are there because some users have been confused about whether or not the agent was running. In my experience, many externally communicating gems do some version of the "I'm on and ready!" announcement, irregardless of whether or not it's a good idea, it raises the question of whether or not it's _expected_ behaviour to announce it.

The alert logger specifically is there because Rails, at the time of loading the railtie, doesn't output its logs to STDOUT which is where most devs (I think) will be looking. Hence the extra logger. Very open to ideas of a better approach if you have any.

It's a balance between when do you want to help those who need it vs. how much do you expect people to figure out themselves.
