### ISSUE TITLE
feature: always capture error sample (transaction_sample_rate)

### ISSUE THREAD

**Issue by Dariusch** [elastic/apm-agent-ruby#480]
Hello,
first of great job with this gem and the Elastic APM Product!

I'd like to issue a feature request regarding the `transaction_sample_rate` configuration.
As a developer of a high throughput application I reduced the sample_rate down to `0.1` to reduce index size.

Is there any way possible to configure the sample_rate for errors?

With a sample rate of `0.1` it might happen that there is no transaction for the error (see picture) because it could have been reduced. This is especially a problem when an error is occuring rarely. 

![image](https://user-images.githubusercontent.com/1800181/62713786-96d64500-b9fd-11e9-86f4-6918ae77e266.png)

Thanks for giving it a thought
Dariusch

**Comment by mikker** [comment]
Hi @Dariusch!

`transaction_sample_rate` doesn't actually affect the amount of transactions – if a transaction isn't sampled, its spans are not recorded but the transaction itself is still. (Otherwise we couldn't calculate the requests/minute graphs for example.)

There's no way currently to reduce the sample rate for errors. If storage is a problem, you can reduce the size by decreasing or even disabling the source code lines from the errors: https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-source-lines-error-app-frames

**Comment by Dariusch** [comment]
> transaction_sample_rate doesn't actually affect the amount of transactions – if a transaction isn't sampled, its spans are not recorded but the transaction itself is still.

My basic idea was:
* reducing the sample rate of non-error transactions to `0.1`. 
* the sample of an error should always be recorded (configuration)

For now I did not have the chance to have a look into your source code so I do not know when the decision of recording/rejecting sample is being made.
Ideally the sample will would rejected at the end the transaction (`transaction_sample_rate`). When the transaction contains an error it would be nice to configure if the sample will be rejected or not.

Thanks for the link I will have a look at it

**Comment by mikker** [comment]
It's a good idea! Yet, as you point out yourself, it would need us to do _tail based_ sampling and currently we only do _head based_ sampling.

The main reason people are turning on sampling is for performance. That's why we need to do it up front.
