### ISSUE TITLE
Add Resque instrumentation and error reporting

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#75]
As Resque (by default) forks the process around every job this was a bit tricky. We want this eventually but for now it's put off until after 1.0.

**Comment by alvarolobato** [comment]
There were some additional problems with this integration (integration with the external process), we've decided to wait after GA to implement this integration.

**Comment by darrellnash** [comment]
Today I upgraded to v2.0.1 of this gem and found our Resque jobs stopped sending data to the apm-server. After some digging through the gem code, I found a workaround:

You want to force the Agent to restart in a fresh state for each newly forked process, which can be done by adding an `after_fork` hook to Resque. For example, you can create a rails initializer such as `config/initializers/resque_initializer.rb`:

```ruby
Resque.after_fork do
  ElasticAPM.stop if ElasticAPM.running?
  ElasticAPM.start
end
```

The problem is that the workers are booted before the fork, and apparently some state in the ConcurrentRuby thread pool doesn't transfer over well to the child process (or maybe just the threads are in a dead state in the child?). So while transactions and spans were getting queued up, there were no worker threads to pull jobs off the queue to send to the apm-server.

When the `ElasticAPM.stop` call was triggered at the end, the ConcurrentRuby `@pool.shutdown` and `@pool.wait_for_termination(5)` calls would work fine because there are no _valid_ worker threads to shutdown, even though there are plenty of queued up messages. And apparently `@workers` still had the initial pre-fork booted worker objects, but again, they weren't actually executing. Rebooting the Agent fixed my woes.

Not the first time mixing multi-threaded and multi-processed models has caused me brain damage ;)

Hope this helps troubleshoot the auto-instrumentation effort.

**Comment by mikker** [comment]
Hi @darrellnash. Resque instrumentation has never been officially supported. As you see it caused us some trouble. Thanks for your thorough investigation and description. I'll take another look at it when the dust of 2.0 settles.

**Comment by tmedford** [comment]
Any chance at supporting resque?

**Comment by mikker** [comment]
I'm afraid the story is still the same as above: We'd love to support Resque but are working on other things at the moment. PRs are welcome 😊

**Comment by sundarv85** [comment]
Any chance of this being supported? As we are also using resque.

**Comment by mikker** [comment]
We are still not actively working on a solution, so the status hasn't changed.

We do however have more devs on the agent now, so perhaps it's time to take another look. I'll bring it up 👍

**Comment by sundarv85** [comment]
@mikker Just following up to see if you were able to bring it up and whether it will be something that will be available anytime soon. Thanks!

**Comment by estolfo** [comment]
@sundarv85 we did discuss it and we will probably start looking into instrumenting Resque soon!

**Comment by estolfo** [comment]
Hello, I've opened a [pull request](https://github.com/elastic/apm-agent-ruby/pull/729) with support for `Resque`
If you have a chance to try it out in your testing environments, I'd welcome your feedback. Thanks!

**Comment by estolfo** [comment]
@sundarv85 I should have tagged you in my previous comment. If you have a chance to try out the pull request, please let me know!
