### ISSUE TITLE
Net/http breaking down with elastic apm

### ISSUE THREAD

**Issue by hashwin** [elastic/apm-agent-ruby#834]
## Describe the bug

Getting this error: URI::InvalidURIError: bad URI(is not URI?): "https://graph.microsoft.com:443https://graph.microsoft.com/v1.0/me/sendMail"
It seems to be prepending the host and the port to the uri itself.

This does not happen when the gem is not included.

## Steps to reproduce
Make a net/http request

## Expected behavior
APM should NOT change any behavior of the code!

## Environment

- **OS**: Linux
- **Ruby version**: 2.6.6
- **Framework and version**: 6.0.3.2
- **APM Server version**: 7.8.0
- **Agent version**: 3.8.0

**Comment by mikker** [comment]
Hi @hashwin! Sorry for taking some time to get back to you.

I haven't been able to reproduce this. Could you perhaps share a code snippet of how you use `net/http` in your application?

**Comment by hashwin** [comment]
@mikker 
```
# frozen_string_literal: true

require "bundler/inline"
require 'net/http'

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.0.3.2"
  gem 'elastic-apm'
  gem 'byebug'
end

require 'elastic-apm'
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    ElasticAPM.start
    ElasticAPM.agent.instrumenter.current_transaction = 'abc'

    uri = URI.parse("https://postman-echo.com/post")
    params = { a: 1, b: 2 }
    
    request = Net::HTTP::Post.new(uri.to_s)
    request.body = params.to_json

    Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      response = http.request(request)
      puts response.body
    end
  end
end
```

**Comment by mikker** [comment]
```diff
-     request = Net::HTTP::Post.new(uri.to_s)
+     request = Net::HTTP::Post.new(uri.path)
```

You're supposed to pass the path to `Post.new`, see https://www.rubydoc.info/stdlib/net/Net/HTTPRequest#initialize-instance_method.

But I take it your code works as is? Then I guess we'll have to support it too somehow.

**Comment by mikker** [comment]
The error by the way is happening inside APM, yes, but it isn't altering behaviour or the original request (other than aborting by raising).

This is where the error happens and the `url` that is altered is only used to set the Span name, etc with information about the request.

**Comment by hashwin** [comment]
https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html suggests that you pass the URI object itself into the constructor. Not sure why "to_s" was used in this case, but FWIW it seems to work fine if the URI is passed in.

**Comment by hashwin** [comment]
In general though, I feel that spies would benefit from having a general rescue method that fails silently rather than affecting the normal working of the code.

**Comment by mikker** [comment]
I see your point. I'll consider rescuing in relevant places 👍

**Comment by lucasklaassen** [comment]
> ```diff
> -     request = Net::HTTP::Post.new(uri.to_s)
> +     request = Net::HTTP::Post.new(uri.path)
> ```
> 
> You're supposed to pass the path to `Post.new`, see https://www.rubydoc.info/stdlib/net/Net/HTTPRequest#initialize-instance_method.
> 
> But I take it your code works as is? Then I guess we'll have to support it too somehow.

@mikker You are correct that you're suppose to pass the path and not the uri to `Post.new` however, the `Post.new` initializer inherits from the base class `HTTPGenericRequest` and it's initializer has support for path argument to be a uri or a path. This leaves room for error as any app developer who uses the net/http library could be wrongly passing the entire uri instead of the path to `Post.new` like this gem does here: https://github.com/blitline-dev/blitline_gem/blob/master/lib/blitline/http_poster.rb#L9-L13 You can see on line 10 that the `path` argument can sometimes be a URI. The original path argument is passed to `Post.new` on line 13 instead of them using `uri.path` which would be the best. However this approach works just fine since `Post.new` supports the path argument as being a URI.

All that said, we ran into a production issue today because the `apm-agent-ruby` gem always assumes that the `path` variable being sent to `Post.new` will be a path and not a uri.

Ideally we should add the same support for the path argument here or rescue these errors from happening as a profiling gem shouldn't cause exceptions in a production application.

Let me know your thoughts, happy to put up a PR.

**Comment by mikker** [comment]
Very enlightening and thorough explanation ❤️ would love a PR!

**Comment by lucasklaassen** [comment]
@mikker PR is up! https://github.com/elastic/apm-agent-ruby/pull/1027
